# Generated by Django 5.2.2 on 2025-06-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_category_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='statud',
            new_name='status',
        ),
    ]
